// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: integration/xray/config.proto

package chitanda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Psk           string                 `protobuf:"bytes,2,opt,name=psk,proto3" json:"psk,omitempty"`
	Level         uint32                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_integration_xray_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_integration_xray_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_integration_xray_config_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *User) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type InboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psk           string                 `protobuf:"bytes,1,opt,name=psk,proto3" json:"psk,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Fallback      string                 `protobuf:"bytes,3,opt,name=fallback,proto3" json:"fallback,omitempty"`
	StrictSni     string                 `protobuf:"bytes,4,opt,name=strict_sni,json=strictSni,proto3" json:"strict_sni,omitempty"`
	Transport     string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	ServerId      string                 `protobuf:"bytes,6,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReplayFile    string                 `protobuf:"bytes,7,opt,name=replay_file,json=replayFile,proto3" json:"replay_file,omitempty"`
	CertFile      string                 `protobuf:"bytes,8,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,9,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	Users         []*User                `protobuf:"bytes,10,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_integration_xray_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_integration_xray_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_integration_xray_config_proto_rawDescGZIP(), []int{1}
}

func (x *InboundConfig) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *InboundConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InboundConfig) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

func (x *InboundConfig) GetStrictSni() string {
	if x != nil {
		return x.StrictSni
	}
	return ""
}

func (x *InboundConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *InboundConfig) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *InboundConfig) GetReplayFile() string {
	if x != nil {
		return x.ReplayFile
	}
	return ""
}

func (x *InboundConfig) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *InboundConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *InboundConfig) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type OutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Psk           string                 `protobuf:"bytes,3,opt,name=psk,proto3" json:"psk,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Transport     string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	PoolSize      int32                  `protobuf:"varint,6,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	ServerId      string                 `protobuf:"bytes,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AllowInsecure bool                   `protobuf:"varint,8,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	AutoScale        bool                   `protobuf:"varint,9,opt,name=auto_scale,json=autoScale,proto3" json:"auto_scale,omitempty"`
	MaxPoolSize      int32                  `protobuf:"varint,10,opt,name=max_pool_size,json=maxPoolSize,proto3" json:"max_pool_size,omitempty"`
	ScaleUpThreshold int32                  `protobuf:"varint,11,opt,name=scale_up_threshold,json=scaleUpThreshold,proto3" json:"scale_up_threshold,omitempty"`
	ScaleDownIdle    int32                  `protobuf:"varint,12,opt,name=scale_down_idle,json=scaleDownIdle,proto3" json:"scale_down_idle,omitempty"`
	Cooldown         int32                  `protobuf:"varint,13,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
	mi := &file_integration_xray_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_integration_xray_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundConfig.ProtoReflect.Descriptor instead.
func (*OutboundConfig) Descriptor() ([]byte, []int) {
	return file_integration_xray_config_proto_rawDescGZIP(), []int{2}
}

func (x *OutboundConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *OutboundConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *OutboundConfig) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *OutboundConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutboundConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *OutboundConfig) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *OutboundConfig) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *OutboundConfig) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *OutboundConfig) GetAutoScale() bool {
	if x != nil {
		return x.AutoScale
	}
	return false
}

func (x *OutboundConfig) GetMaxPoolSize() int32 {
	if x != nil {
		return x.MaxPoolSize
	}
	return 0
}

func (x *OutboundConfig) GetScaleUpThreshold() int32 {
	if x != nil {
		return x.ScaleUpThreshold
	}
	return 0
}

func (x *OutboundConfig) GetScaleDownIdle() int32 {
	if x != nil {
		return x.ScaleDownIdle
	}
	return 0
}

func (x *OutboundConfig) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

var File_integration_xray_config_proto protoreflect.FileDescriptor

const file_integration_xray_config_proto_rawDesc = "" +
	"\n" +
	"\x1dintegration/xray/config.proto\x12\x13xray.proxy.chitanda\"D\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03psk\x18\x02 \x01(\tR\x03psk\x12\x14\n" +
	"\x05level\x18\x03 \x01(\rR\x05level\"\xb5\x02\n" +
	"\rInboundConfig\x12\x10\n" +
	"\x03psk\x18\x01 \x01(\tR\x03psk\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bfallback\x18\x03 \x01(\tR\bfallback\x12\x1d\n" +
	"\n" +
	"strict_sni\x18\x04 \x01(\tR\tstrictSni\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\x12\x1b\n" +
	"\tserver_id\x18\x06 \x01(\tR\bserverId\x12\x1f\n" +
	"\vreplay_file\x18\a \x01(\tR\n" +
	"replayFile\x12\x1b\n" +
	"\tcert_file\x18\b \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\t \x01(\tR\akeyFile\x12/\n" +
	"\x05users\x18\n" +
	" \x03(\v2\x19.xray.proxy.chitanda.UserR\x05users\"\xee\x01\n" +
	"\x0eOutboundConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x10\n" +
	"\x03psk\x18\x03 \x01(\tR\x03psk\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\x12\x1b\n" +
	"\tpool_size\x18\x06 \x01(\x05R\bpoolSize\x12\x1b\n" +
	"\tserver_id\x18\a \x01(\tR\bserverId\x12%\n" +
	"\x0eallow_insecure\x18\b \x01(\bR\rallowInsecureB[\n" +
	"\x17com.xray.proxy.chitandaP\x01Z(github.com/xtls/xray-core/proxy/chitanda\xaa\x02\x13Xray.Proxy.Chitandab\x06proto3"

var (
	file_integration_xray_config_proto_rawDescOnce sync.Once
	file_integration_xray_config_proto_rawDescData []byte
)

func file_integration_xray_config_proto_rawDescGZIP() []byte {
	file_integration_xray_config_proto_rawDescOnce.Do(func() {
		file_integration_xray_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_xray_config_proto_rawDesc), len(file_integration_xray_config_proto_rawDesc)))
	})
	return file_integration_xray_config_proto_rawDescData
}

var file_integration_xray_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_integration_xray_config_proto_goTypes = []any{
	(*User)(nil),           // 0: xray.proxy.chitanda.User
	(*InboundConfig)(nil),  // 1: xray.proxy.chitanda.InboundConfig
	(*OutboundConfig)(nil), // 2: xray.proxy.chitanda.OutboundConfig
}
var file_integration_xray_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.chitanda.InboundConfig.users:type_name -> xray.proxy.chitanda.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_integration_xray_config_proto_init() }
func file_integration_xray_config_proto_init() {
	if File_integration_xray_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_xray_config_proto_rawDesc), len(file_integration_xray_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_xray_config_proto_goTypes,
		DependencyIndexes: file_integration_xray_config_proto_depIdxs,
		MessageInfos:      file_integration_xray_config_proto_msgTypes,
	}.Build()
	File_integration_xray_config_proto = out.File
	file_integration_xray_config_proto_goTypes = nil
	file_integration_xray_config_proto_depIdxs = nil
}
